spring:
  redis:
    pool:
      min-idle: 0
      max-idle: 10
      max-active: 20
      max-wait: 5000
    cluster:
      nodes: 10.150.8.113:7001,10.150.8.107:7003,10.150.8.143:7005
      maxRedirects: 5
      timeout: 5000
      expireSeconds: 259200
    password: test@123456
    prefix: "myPrefix:"
